version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ARANGO_ROOT_PASSWORD=mypassword
    depends_on:
      - arango

  arango:
    image: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=mypassword
    volumes:
      - arango-db:/var/lib/arangodb3
volumes:
  arango-db:
